title: William Reading Tobin
description: Public-facing work in HPC, scientific software, numerical methods, and computational science.
url: https://www.wrtobin.com
google_analytics:
show_downloads: false
markdown: kramdown

plugins:
  - jekyll-mentions

collections:
  articles:
    output: true
    permalink: /articles/:name/

defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: article
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - cv/cv.tex
